version: "3.3"

services:
  db:
    image: postgres
    container_name: docker-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: d3kTrklm54208
      POSTGRES_DB: docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: docker-api
    build: .
    depends_on:
      - db
    container_name: docker-api
    restart: unless-stopped
    environment:
      NODE_ENV: docker
      ADMIN_NAME: "etienne"
      ADMIN_PASSWORD: "etienne"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
