version: "3.3"

services:
  db:
    image: postgres
    container_name: docker-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: d3kTrklm54208
      POSTGRES_DB: docker
  api:
    image: docker-api
    build: .
    depends_on:
      - db
    container_name: docker-api
    restart: unless-stopped
    environment:
      NODE_ENV: docker
      ADMIN_NAME: etienne
      ADMIN_PASSWORD: etienne
      JWT_SECRET: 5Eq!j89s3*Ys
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: docker_user
      DB_PASSWORD: d3kTrklm54208
      DB_NAME: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
